export interface ProductItem {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  isVeg: boolean;
  badge?: string;
  categorySlug: string;
}

export interface CategoryItem {
  id: string;
  name: string;
  slug: string;
  icon: string;
  sortOrder: number;
}

export interface BannerItem {
  id: string;
  title: string;
  subtitle: string;
  tag: string;
  badge: string;
  imageUrl: string;
}

export const INITIAL_BANNERS: BannerItem[] = [
  {
    id: 'banner-1',
    title: 'Asian Bites & Dimsums',
    subtitle: 'Get 20% OFF on Dimsums & Small Bites',
    tag: 'CHEF SPECIAL',
    badge: 'POTS20',
    imageUrl: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'banner-2',
    title: 'Summer Specials Feast',
    subtitle: 'Watermelon Feta Salad & Stuffed Ravioli',
    tag: 'SEASONAL TREAT',
    badge: 'SUMMERFEAST',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'banner-3',
    title: 'Classic Thin Crust Pizzas',
    subtitle: 'Flat ₹100 OFF on Orders Above ₹500',
    tag: 'COFFEE & BITES',
    badge: 'STONES100',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_CATEGORIES: CategoryItem[] = [
  { id: 'cat-1', name: 'Asian Small Bites', slug: 'asian-bites', icon: '🥟', sortOrder: 1 },
  { id: 'cat-2', name: 'Summer Specials', slug: 'summer-specials', icon: '🥗', sortOrder: 2 },
  { id: 'cat-3', name: 'Thin Crust Pizzas', slug: 'classic-pizzas', icon: '🍕', sortOrder: 3 },
  { id: 'cat-4', name: 'Artisanal Shakes', slug: 'craft-shakes', icon: '🥤', sortOrder: 4 },
  { id: 'cat-5', name: 'Desserts & Bakery', slug: 'desserts', icon: '🍰', sortOrder: 5 },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  // Asian Small Bites
  {
    id: 'prod-veggie-dimsums',
    name: 'Classic Veggie Dimsums',
    description: 'Soft steamed dumplings stuffed with finely chopped garden vegetables and aromatic seasoning',
    price: 399,
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Bestseller',
    categorySlug: 'asian-bites',
  },
  {
    id: 'prod-chilli-oil-chicken-dimsums',
    name: 'Chilli Oil Chicken Dimsums',
    description: 'Tender chicken dimsums tossed with house-made fiery chili garlic oil',
    price: 459,
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Popular',
    categorySlug: 'asian-bites',
  },
  {
    id: 'prod-chilli-oil-mutton-dimsums',
    name: 'Chilli Oil Mutton Dimsums',
    description: 'Succulent minced mutton dumplings topped with signature crispy chilli garlic oil',
    price: 659,
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Chef Special',
    categorySlug: 'asian-bites',
  },
  {
    id: 'prod-honey-chilli-potato',
    name: 'Honey Chilli Potato',
    description: 'Crispy golden potato fingers tossed in sweet & spicy sesame honey glaze',
    price: 489,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Crunchy',
    categorySlug: 'asian-bites',
  },
  {
    id: 'prod-dynamite-prawns',
    name: 'Dynamite Prawns',
    description: 'Crispy fried prawns coated in spicy sriracha mayo dynamite sauce',
    price: 799,
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Must Try',
    categorySlug: 'asian-bites',
  },
  {
    id: 'prod-chilli-paneer',
    name: 'Chilli Paneer',
    description: 'Cottage cheese cubes wok-tossed with crisp bell peppers, onions & spicy soya glaze',
    price: 499,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Classic',
    categorySlug: 'asian-bites',
  },
  {
    id: 'prod-chilli-mushroom',
    name: 'Chilli Mushroom',
    description: 'Button mushrooms stir-fried with green chillies, garlic & savory dark sauce',
    price: 499,
    image: 'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Popular',
    categorySlug: 'asian-bites',
  },
  {
    id: 'prod-korean-fried-chicken',
    name: 'Korean Fried Chicken',
    description: 'Double crunch fried chicken glazed with sweet, tangy & spicy Gochujang sauce',
    price: 549,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Trending',
    categorySlug: 'asian-bites',
  },
  {
    id: 'prod-veg-spring-rolls',
    name: 'Veg Spring Rolls',
    description: 'Golden crispy rolls stuffed with shredded vegetables & served with sweet chilli dip',
    price: 349,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Snack',
    categorySlug: 'asian-bites',
  },
  {
    id: 'prod-cheese-corn-spring-rolls',
    name: 'Cheese & Corn Spring Rolls',
    description: 'Crispy spring rolls stuffed with gooey melted mozzarella & sweet corn',
    price: 389,
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Cheesy',
    categorySlug: 'asian-bites',
  },
  {
    id: 'prod-chicken-spring-rolls',
    name: 'Chicken Spring Rolls',
    description: 'Deep fried spring rolls filled with seasoned tender minced chicken',
    price: 429,
    image: 'https://images.unsplash.com/photo-1548365328-8c6db4b6339f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Crunchy',
    categorySlug: 'asian-bites',
  },

  // Chef's Summer Specials
  {
    id: 'prod-watermelon-feta-salad',
    name: 'Watermelon Feta Salad',
    description: 'Light crisp hydrating watermelon cubes, crumbled feta cheese, mint sprigs & balsamic drizzle',
    price: 479,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Refreshing',
    categorySlug: 'summer-specials',
  },
  {
    id: 'prod-avocado-mango-salad',
    name: 'Avocado & Mango Salad',
    description: 'Tender avocado tossed with sun-ripened mangoes & our house-made balsamic vinaigrette',
    price: 519,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Chef Special',
    categorySlug: 'summer-specials',
  },
  {
    id: 'prod-spinach-ricotta-ravioli',
    name: 'Spinach Ricotta Ravioli',
    description: 'Delicate handmade ravioli stuffed with spinach & ricotta with light house-made pomodoro puree',
    price: 659,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Signature',
    categorySlug: 'summer-specials',
  },
  {
    id: 'prod-spinach-feta-cannelloni',
    name: 'Spinach & Feta Cannelloni',
    description: 'Hand rolled pasta tubes stuffed with baby spinach & feta, baked with pomodoro sauce and mozzarella',
    price: 599,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281292?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Must Try',
    categorySlug: 'summer-specials',
  },
  {
    id: 'prod-tender-chicken-cannelloni',
    name: 'Tender Chicken Cannelloni',
    description: 'Hand rolled pasta tubes stuffed with tender chicken, baked with pomodoro sauce and melted mozzarella',
    price: 659,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Popular',
    categorySlug: 'summer-specials',
  },

  // Thin Crust Pizzas
  {
    id: 'prod-classic-margherita',
    name: 'Classic Margherita',
    description: 'Classic thin crust pizza with basil, tomato sauce & 100% mozzarella cheese',
    price: 429,
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Classic',
    categorySlug: 'classic-pizzas',
  },
  {
    id: 'prod-exotic-extravaganza',
    name: 'Exotic Extravaganza',
    description: 'Broccoli, bell peppers, zucchini, button mushrooms in authentic marinara base',
    price: 519,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Loaded',
    categorySlug: 'classic-pizzas',
  },
  {
    id: 'prod-classic-mexicana',
    name: 'Classic Mexicana',
    description: 'Mushroom, sliced onions, jalapenos, sweet corn and zesty marinara sauce',
    price: 529,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Spicy',
    categorySlug: 'classic-pizzas',
  },
  {
    id: 'prod-cheesy-garlic-pizza',
    name: 'Cheesy Garlic Pizza',
    description: 'Roasted garlic, tomato, fresh basil & melted mozzarella cheese on marinara',
    price: 489,
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Bestseller',
    categorySlug: 'classic-pizzas',
  },
  {
    id: 'prod-wild-wild-west',
    name: 'Wild Wild West',
    description: 'Tri-coloured bell peppers with sweet corn and signature marinara sauce',
    price: 509,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Popular',
    categorySlug: 'classic-pizzas',
  },
  {
    id: 'prod-butter-chicken-pizza',
    name: 'Butter Chicken Pizza',
    description: 'Indian fusion delight topped with rich creamy butter chicken gravy & cheese',
    price: 539,
    image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Chef Special',
    categorySlug: 'classic-pizzas',
  },
  {
    id: 'prod-chicken-tikka-pizza',
    name: 'Chicken Tikka Pizza',
    description: 'Spicy chicken tikka chunks with marinara, sliced red onions & fresh tomato',
    price: 529,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Must Try',
    categorySlug: 'classic-pizzas',
  },
  {
    id: 'prod-chicken-alfredo-pizza',
    name: 'Chicken Alfredo Pizza',
    description: 'Rich Alfredo cream base topped with chicken, mushrooms & mozzarella cheese',
    price: 549,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Creamy',
    categorySlug: 'classic-pizzas',
  },
  {
    id: 'prod-barbeque-chicken-pizza',
    name: 'Barbeque Chicken Pizza',
    description: 'Topped with bell peppers, onion & barbeque sauce on marinara base',
    price: 539,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Smoky',
    categorySlug: 'classic-pizzas',
  },
  {
    id: 'prod-cheesy-garlic-polo',
    name: 'Cheesy Garlic Polo Pizza',
    description: 'Roasted garlic, tomato, seasoned chicken, marinara & mozzarella',
    price: 539,
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Popular',
    categorySlug: 'classic-pizzas',
  },

  // Artisanal Shakes
  {
    id: 'prod-strawberry-swirl',
    name: 'Strawberry Swirl Shake',
    description: 'Strawberry compote blended with vanilla ice cream and fresh milk',
    price: 299,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Fruity',
    categorySlug: 'craft-shakes',
  },
  {
    id: 'prod-kitkat-shake',
    name: 'Kitkat Shake',
    description: 'Chocolate milkshake blended with KitKat chocolate bars & cocoa crunch',
    price: 339,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Bestseller',
    categorySlug: 'craft-shakes',
  },
  {
    id: 'prod-oriental-mango',
    name: 'Oriental Mango Shake',
    description: 'Mango puree blended with rich vanilla ice cream and chilled milk',
    price: 319,
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Tropical',
    categorySlug: 'craft-shakes',
  },
  {
    id: 'prod-nutty-scotch',
    name: 'Nutty Scotch Shake',
    description: 'Butterscotch sauce & praline crumbs blended with ice cream and milk',
    price: 319,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Crunchy',
    categorySlug: 'craft-shakes',
  },
  {
    id: 'prod-blueberry-coconut',
    name: 'Blueberry Coconut Shake',
    description: 'Blueberry sauce and coconut shavings blended with ice cream',
    price: 359,
    image: 'https://images.unsplash.com/photo-1553787499-6f9133860278?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Exotic',
    categorySlug: 'craft-shakes',
  },
  {
    id: 'prod-choco-blast',
    name: 'Choco Blast Shake',
    description: 'Chocolate sauce & ice cream blended with milk for an intense cocoa punch',
    price: 319,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Rich',
    categorySlug: 'craft-shakes',
  },
  {
    id: 'prod-chocolate-fudge-brownie',
    name: 'Chocolate Fudge Brownie Shake',
    description: 'Decadent shake with chocolate brownie bits, ice cream & milk',
    price: 339,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Decadent',
    categorySlug: 'craft-shakes',
  },
  {
    id: 'prod-oreo-cookies-shake',
    name: 'Oreo Cookies Shake',
    description: 'Vanilla ice cream blended with crushed Oreo cookies and chilled milk',
    price: 339,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Classic',
    categorySlug: 'craft-shakes',
  },
  {
    id: 'prod-exotic-kiwi',
    name: 'Exotic Kiwi Shake',
    description: 'Kiwi sauce blended with ice cream and milk for a refreshing twist',
    price: 319,
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Refreshing',
    categorySlug: 'craft-shakes',
  },

  // Desserts & Bakery
  {
    id: 'prod-baked-cheesecake',
    name: 'Baked Cheesecake',
    description: 'Classic velvety New York style baked cheesecake on a buttery crust',
    price: 379,
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Must Try',
    categorySlug: 'desserts',
  },
  {
    id: 'prod-choco-truffle-cake',
    name: 'Choco Truffle Cake',
    description: 'Rich dark chocolate cake layered with silky chocolate truffle glaze',
    price: 379,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Bestseller',
    categorySlug: 'desserts',
  },
  {
    id: 'prod-banoffee-pie',
    name: 'Banoffee Pie',
    description: 'English dessert pie made with bananas, whipped cream & thick caramel toffee',
    price: 369,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Chef Special',
    categorySlug: 'desserts',
  },
];
